dist: focal

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov
      - libgtest-dev

before_script:
  - git submodule add https://github.com/google/googletest.git gtest
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_TESTS=ON -DENABLE_COVERAGE=ON ..

script:
  - make
  - make test

after_success:
  - git submodule deinit -f -- gtest
  - rm -rf .git/modules/gtest
  - git rm -f gtest
  - lcov --capture --directory . --output-file coverage_total.info
  - lcov --remove coverage_total.info '/usr/*' --output-file coverage_total.info
  - lcov --remove coverage_total.info 'gtest/*' --output-file coverage_total.info
  - lcov --list coverage_total.info
  - bash <(curl -s https://codecov.io/bash) -f coverage_total.info || echo "Codecov did not collect coverage reports"
